apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - migration-job.yaml
  - servicemonitor.yaml

configMapGenerator:
  - name: video-api-migrations-sql
    files:
      - ../../../../video-api/src/main/resources/db/migration/V1__init.sql
      - ../../../../video-api/src/main/resources/db/migration/V2__users.sql
      - ../../../../video-api/src/main/resources/db/migration/V3__admin_role.sql
      - ../../../../video-api/src/main/resources/db/migration/V4__outbox_correlation_id.sql
      - ../../../../video-api/src/main/resources/db/migration/V5__outbox_lease.sql
      - ../../../../video-api/src/main/resources/db/migration/V6__must_change_password.sql
      - ../../../../video-api/src/main/resources/db/migration/V7__video_file_size.sql
      - ../../../../video-api/src/main/resources/db/migration/V8__admin_seed_password_placeholder.sql
      - ../../../../video-api/src/main/resources/db/migration/V9__outbox_lock_token.sql
      - ../../../../video-api/src/main/resources/db/migration/V10__tokens_valid_after.sql
      - ../../../../video-api/src/main/resources/db/migration/V11__recover_admin_password_upgrade.sql
      - ../../../../video-api/src/main/resources/db/migration/beforeMigrate.sql
      - ../../../../video-api/src/main/resources/db/migration/V12__storage_cleanup.sql
