apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fiapx
resources:
  - configmap.yaml
  - ingress.yaml
  - video-gateway
  - video-api
  - video-worker
  - notification-worker
  - web
