/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users/me/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Troca a senha do usuário autenticado
     * @description Exige a senha atual. Usado tanto pra troca voluntária quanto pra sair do estado "deve trocar a senha" do usuário admin semeado (ver LoginResponse.mustChangePassword). Retorna um token novo: a troca de senha revoga qualquer token emitido antes dela (incluindo o que autenticou esta própria requisição), então o chamador precisa trocar pelo token da resposta pra continuar autenticado.
     */
    put: operations['changePassword']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/videos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Lista os vídeos do usuário autenticado
     * @description Listagem paginada, opcionalmente filtrada por status. Nunca retorna vídeos de outros usuários.
     */
    get: operations['list']
    put?: never
    /**
     * Envia um vídeo para processamento
     * @description Faz upload de um arquivo de vídeo (multipart), persiste com status QUEUED e publica um evento assíncrono para o video-worker extrair os frames. Formatos aceitos: mp4, mov, avi, mkv, webm (ver VideoFormatValidator).
     */
    post: operations['upload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cria um novo usuário
     * @description Senha é armazenada com hash BCrypt. E-mail precisa ser único.
     */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Autentica e retorna um JWT
     * @description Rate limit de 5 tentativas falhas por e-mail a cada 60s (Redis, INCR+TTL); ao atingir o limite, retorna 429 mesmo com credenciais corretas até a janela expirar.
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/videos/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Consulta o status de um vídeo
     * @description 404 tanto para vídeo inexistente quanto para vídeo de outro usuário — não vaza a existência de um recurso alheio.
     */
    get: operations['getStatus']
    put?: never
    post?: never
    /**
     * Exclui um vídeo
     * @description Remove o registro e os arquivos no storage (original e, se existir, o zip processado). Um administrador pode excluir vídeo de qualquer usuário; um usuário comum só o próprio.
     */
    delete: operations['delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/videos/{id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Baixa o zip de frames de um vídeo já processado
     * @description Retorna o zip como application/octet-stream, transmitido diretamente do storage (proxy de bytes) — não uma URL pré-assinada.
     */
    get: operations['download']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/videos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Lista todos os vídeos do sistema
     * @description Paginado, de qualquer usuário, com o e-mail do dono de cada vídeo.
     */
    get: operations['listVideos']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Lista todos os usuários cadastrados
     * @description Paginado, sem escopo por dono.
     */
    get: operations['listUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Exclui um usuário
     * @description Exclusão em cascata: apaga todos os vídeos do usuário (registro + arquivos no storage) antes da própria conta.
     */
    delete: operations['deleteUser']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Troca de senha do próprio usuário autenticado */
    ChangePasswordRequest: {
      /**
       * @description Senha atual, pra confirmar que é o dono da conta
       * @example Admin@123
       */
      currentPassword: string
      /**
       * @description 8 a 100 caracteres — armazenada com hash BCrypt, nunca em texto puro
       * @example nova-senha-secreta-123
       */
      newPassword: string
    }
    /** @description Token de acesso emitido após login bem-sucedido */
    LoginResponse: {
      /**
       * @description JWT HS256 assinado
       * @example eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI...
       */
      accessToken?: string
      /**
       * @description Sempre "Bearer"
       * @example Bearer
       */
      tokenType?: string
      /**
       * Format: int64
       * @description Validade do token em segundos
       * @example 1800
       */
      expiresIn?: number
      /**
       * @description Papel do usuário autenticado
       * @example USER
       * @enum {string}
       */
      role?: 'USER' | 'ADMIN'
      /**
       * @description true quando o usuário precisa trocar a senha antes de continuar — o frontend deve redirecionar direto pra tela de troca de senha, sem deixar navegar pro resto da aplicação
       * @example false
       */
      mustChangePassword?: boolean
    }
    /** @description Confirmação de upload aceito para processamento */
    VideoUploadResponse: {
      /**
       * Format: uuid
       * @description ID gerado do vídeo
       */
      id?: string
      /**
       * @description Sempre QUEUED nesta resposta — o processamento é assíncrono
       * @enum {string}
       */
      status?: 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
    }
    /** @description Dados de cadastro de um novo usuário */
    RegisterRequest: {
      /**
       * Format: email
       * @description E-mail único — cadastro é rejeitado se já existir
       * @example user@fiapx.com
       */
      email: string
      /**
       * @description 8 a 100 caracteres — armazenada com hash BCrypt, nunca em texto puro
       * @example senha-secreta-123
       */
      password: string
    }
    /** @description Usuário recém-criado */
    RegisterResponse: {
      /**
       * Format: uuid
       * @description ID gerado do usuário
       */
      id?: string
      /**
       * @description E-mail cadastrado
       * @example user@fiapx.com
       */
      email?: string
    }
    /** @description Credenciais de login */
    LoginRequest: {
      /**
       * Format: email
       * @description E-mail cadastrado
       * @example user@fiapx.com
       */
      email: string
      /**
       * @description Senha em texto puro (nunca logada nem persistida em claro)
       * @example senha-secreta-123
       */
      password: string
    }
    /** @description Página de resultados da listagem de vídeos do usuário autenticado */
    VideoListResponse: {
      /** @description Vídeos da página atual */
      items?: components['schemas']['VideoStatusResponse'][]
      /**
       * Format: int32
       * @description Página atual (0-based)
       * @example 0
       */
      page?: number
      /**
       * Format: int32
       * @description Tamanho de página solicitado
       * @example 20
       */
      size?: number
      /**
       * Format: int64
       * @description Total de vídeos do usuário, somando todas as páginas
       */
      totalElements?: number
    }
    /** @description Status atual de um vídeo no pipeline de processamento */
    VideoStatusResponse: {
      /**
       * Format: uuid
       * @description ID do vídeo
       */
      id?: string
      /**
       * Format: uuid
       * @description ID do usuário dono do vídeo
       */
      userId?: string
      /**
       * @description Nome original do arquivo enviado
       * @example ferias-praia.mp4
       */
      originalFilename?: string
      /**
       * Format: int64
       * @description Tamanho do arquivo enviado, em bytes — null para vídeos enfileirados antes desse campo existir
       * @example 10485760
       */
      fileSizeBytes?: number | null
      /**
       * @description QUEUED → PROCESSING → COMPLETED ou FAILED
       * @enum {string}
       */
      status?: 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
      /** @description Motivo da falha — presente só quando status=FAILED */
      errorMessage?: string | null
      /**
       * Format: date-time
       * @description Data/hora do upload
       */
      createdAt?: string
      /**
       * Format: date-time
       * @description Data/hora da última mudança de status
       */
      updatedAt?: string
    }
    /** @description Página de resultados da listagem de vídeos (admin) */
    AdminVideoListResponse: {
      /** @description Vídeos da página atual */
      items?: components['schemas']['AdminVideoResponse'][]
      /**
       * Format: int32
       * @description Página atual (0-based)
       * @example 0
       */
      page?: number
      /**
       * Format: int32
       * @description Tamanho de página solicitado
       * @example 20
       */
      size?: number
      /**
       * Format: int64
       * @description Total de vídeos do sistema, somando todas as páginas
       */
      totalElements?: number
    }
    /** @description Vídeo com dados do dono — usado só na listagem admin, para não poluir o VideoStatusResponse do usuário comum com um campo que só faz sentido pra admin. */
    AdminVideoResponse: {
      /**
       * Format: uuid
       * @description ID do vídeo
       */
      id?: string
      /**
       * Format: uuid
       * @description ID do usuário dono do vídeo
       */
      userId?: string
      /** @description E-mail do usuário dono do vídeo */
      ownerEmail?: string | null
      /**
       * @description Nome original do arquivo enviado
       * @example ferias-praia.mp4
       */
      originalFilename?: string
      /**
       * @description QUEUED → PROCESSING → COMPLETED ou FAILED
       * @enum {string}
       */
      status?: 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
      /** @description Motivo da falha — presente só quando status=FAILED */
      errorMessage?: string | null
      /**
       * Format: date-time
       * @description Data/hora do upload
       */
      createdAt?: string
      /**
       * Format: date-time
       * @description Data/hora da última mudança de status
       */
      updatedAt?: string
    }
    /** @description Página de resultados da listagem de usuários (admin) */
    AdminUserListResponse: {
      /** @description Usuários da página atual */
      items?: components['schemas']['AdminUserResponse'][]
      /**
       * Format: int32
       * @description Página atual (0-based)
       * @example 0
       */
      page?: number
      /**
       * Format: int32
       * @description Tamanho de página solicitado
       * @example 20
       */
      size?: number
      /**
       * Format: int64
       * @description Total de usuários cadastrados, somando todas as páginas
       */
      totalElements?: number
    }
    /** @description Usuário cadastrado — nunca inclui o hash da senha */
    AdminUserResponse: {
      /**
       * Format: uuid
       * @description ID do usuário
       */
      id?: string
      /** @description E-mail de login */
      email?: string
      /**
       * @description Papel do usuário
       * @enum {string}
       */
      role?: 'USER' | 'ADMIN'
      /**
       * Format: date-time
       * @description Data/hora do cadastro
       */
      createdAt?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  changePassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest']
      }
    }
    responses: {
      /** @description Senha alterada — token novo na resposta */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Nova senha fora do padrão (8 a 100 caracteres) */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Senha atual incorreta */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list: {
    parameters: {
      query?: {
        /** @description Filtro opcional por status */
        status?: 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
        /** @description Página, começando em 0 */
        page?: number
        /** @description Itens por página (máx. 100) */
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VideoListResponse']
        }
      }
      /** @description Token ausente, inválido ou expirado */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  upload: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description Arquivo de vídeo (mp4, mov, avi, mkv ou webm)
           */
          file: string
        }
      }
    }
    responses: {
      /** @description Vídeo aceito e enfileirado para processamento */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VideoUploadResponse']
        }
      }
      /** @description Formato de vídeo não suportado */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Token ausente, inválido ou expirado */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Usuário criado */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegisterResponse']
        }
      }
      /** @description Payload inválido (e-mail malformado, senha curta, etc.) */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description E-mail já cadastrado */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Autenticado */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description E-mail ou senha inválidos */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Rate limit de tentativas de login excedido */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID do vídeo */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VideoStatusResponse']
        }
      }
      /** @description Token ausente, inválido ou expirado */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Vídeo não encontrado (ou pertence a outro usuário) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID do vídeo */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Vídeo excluído */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Token ausente, inválido ou expirado */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Vídeo não encontrado (ou pertence a outro usuário) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  download: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID do vídeo */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Zip com os frames extraídos */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/octet-stream': string
        }
      }
      /** @description Token ausente, inválido ou expirado */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Vídeo não encontrado (ou pertence a outro usuário) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Vídeo ainda não está com status COMPLETED */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  listVideos: {
    parameters: {
      query?: {
        /** @description Filtro opcional por status */
        status?: 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
        /** @description Filtro opcional — substring do nome do arquivo, sem diferenciar maiúsculas/minúsculas */
        filename?: string
        /** @description Página, começando em 0 */
        page?: number
        /** @description Itens por página (máx. 100) */
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminVideoListResponse']
        }
      }
      /** @description Usuário autenticado não é admin */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  listUsers: {
    parameters: {
      query?: {
        /** @description Filtro opcional — substring do e-mail, sem diferenciar maiúsculas/minúsculas */
        email?: string
        /** @description Página, começando em 0 */
        page?: number
        /** @description Itens por página (máx. 100) */
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminUserListResponse']
        }
      }
      /** @description Usuário autenticado não é admin */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  deleteUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Usuário excluído */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Usuário autenticado não é admin */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Usuário não encontrado */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
